apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-6nap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-6nap
    app.kubernetes.io/part-of: ci1t-830-0066-app
  name: devfile-sample-6nap
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-6nap
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-6nap
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0066-tenant/ci1t-830-0066-app/devfile-sample-6nap@sha256:e7d845c7d8c2e0ad894c2fba192a1996e0c15991580a5ef5408016f0143e22bb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
